name: Deploy to AWS

on:
  push:
    branches: [main] # or your default branch

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: maths-advantage-staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          # Move to the correct directory
          cd maths-advantage

          # Verify next.config.ts exists
          ls -la next.config.ts

          # Cleanup before building
          docker system prune -af --volumes

          # Build with debugging enabled
          DOCKER_BUILDKIT=1 docker build \
            --platform linux/amd64 \
            --progress=plain \
            --no-cache \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          # Push the image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_STAGING_SSH_KEY }}
          script: |
            # Aggressive cleanup first
            docker system prune -af --volumes
            docker image prune -af

            # Remove all containers and images
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker rmi $(docker images -q) || true

            # Clear Docker build cache
            docker builder prune -af

            # Check available space
            df -h /

            # Get ECR login token and login
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            # Pull and run new image
            docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

            # Run with memory limits
            docker run -d \
              --memory=2g \
              --memory-swap=2g \
              -p 80:3000 \
              ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

            # Verify container is running
            docker ps
            df -h /

      - name: Clean up old images
        run: |
          # More aggressive cleanup
          docker image prune -a --force
          docker builder prune -af
